### ISSUE TITLE
about labelfusion

### ISSUE THREAD

**Issue by hz-ants** [hygxy/ma_densefusion#1]
Hello!I'd like to ask you some questions about labelfusion.Is it convenient to leave a contact information?My email address:hzcisco@126.com,Thank you!

**Comment by hygxy** [comment]
You can just post your question here so that it benefits everyone

**Comment by hz-ants** [comment]
What I download is the 5g official data set.Pull to the image and run_alignment_tool  in the container,there are the following errors:root@8d33463db38f:~/labelfusion/data/2017-06-15-73# run_alignment_tool
Opening object alignment tool...
log folder: data/2017-06-15-73
ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 404
vtkXOpenGLRenderWindow (0x4426800): Could not find a decent visual


ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 404
vtkXOpenGLRenderWindow (0x4426800): Could not find a decent visual


ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 404
vtkXOpenGLRenderWindow (0x48debb0): Could not find a decent visual


ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Rendering/vtkXOpenGLRenderWindow.cxx, line 404
vtkXOpenGLRenderWindow (0x48debb0): Could not find a decent visual


Traceback (most recent call last):
  File "/root/labelfusion/scripts/labelFusionApp.py", line 79, in <module>
    globalsDict=globals())
  File "/root/labelfusion/modules/labelfusion/setup.py", line 38, in setupLabelFusionDirector
    firstFrameToWorldTransform = utils.getFirstFrameToWorldTransform(filenames['transforms'])
TypeError: 'NoneType' object has no attribute '__getitem__'
Done.
Do you want to install and compile QT,VTK,Director,orothers locally?
  Thank you!

**Comment by hygxy** [comment]
No, I did everything inside docker. Your problem seems like a graphics diver issue. Maybe try some similiar threads on Github?
https://github.com/CDAT/cdat/issues/1134
https://stackoverflow.com/questions/39082920/vtkxopenglrenderwindow-error-in-a-terminal-in-vnc

**Comment by hz-ants** [comment]
My computer kernel is 4.15.112-generic,GPU is gtx1070 and driver is 430.26.After installation,the nvidia-smi test ins normal,CUDA version is 8.0.61,CUDA samples are normal,and OPenGL is also tested,and the results are normal.Installed ros-kinetic ,it can't solve the problem.Tried  to replace the system kernel,disable x service,driver version,CUDA version It's all like this!Later,I installed and compiled vtk5.10.1 again,and the problem was solved!However,due to network reasons,directorpthon failed to compile successfully.I don't know the reason for the above problems,can you tell me?Thank you!

**Comment by hygxy** [comment]
what's the error message?

**Comment by hz-ants** [comment]
/root/labelfusion/scripts/bin/run_alignment_tool: line 9:    23 Aborted                 (core dumped) directorPython $LABELFUSION_SOURCE_DIR/scripts/labelFusionApp.py --logFolder $up_dir/$current_dir --bot-config $LABELFUSION_SOURCE_DIR/config/bot_frames.cfg

**Comment by hz-ants** [comment]
Normally speaking,docker is similar to a virtual machine.You don't need to install some dependencies and libraries locally.But why do I have some problems when I can enter the docker? After pulling my dataset into docker(sudo ./docker_run.sh /home/x/LabelFusion/data/  root@f022359d75f4:~/labelfusion/data/logs/2017-06-13-29# run_alignment_tool
 )  Do you need other local operations to clone the environment?Is it convenient to share your .stl files or datasets?

**Comment by hygxy** [comment]
I myself created the dataset, which takes time and effort, so I don`t wanna share it for free. Your problem is IMO not related to the dataset though. The error message you provided just shows line 9 is the bug location, can you check that file and see which code exactly line 9 is?

**Comment by hz-ants** [comment]
In line 9,is labelfusionApp.py,The camera matrix may not be obtained in import drcargs cameraview and lcmbotcore.The point cloud can't be initialized with openni. Is openni 1 or 2?I try to install and compile it and PCL.To sum up,it may be series of problems caused by Qvtkwidget .I use solidworks to make model

**Comment by hygxy** [comment]
I used realsense d435 as the camera for this project

**Comment by hz-ants** [comment]
I found the key to the above problem,because of the dockers CE version and openGl,so I solved is,thank you!
