### ISSUE TITLE
Using LineMod Datasets

### ISSUE THREAD

**Issue by WinglokWong616** [hygxy/ma_densefusion#5]
Great Work! I am currently trying to evaluate your works with ROS in my own computer, wondering if it's possible to choose LineMod Datasets as training data and test real-time pose estimation with real LineMod objects. Where should I put the RGB, Depth images, "gt.yml", etc? Do I still need to use "generatedataset.py"?
My team will really appreciate it if you respond. It will be of much help to us.

**Comment by hygxy** [comment]
hey glad to hear that. Just put them in the "datasets/data/01/RGB(depth, mask)" folder, I delete the pictures so I can open-source this repo. No, in that case, you don't need generatedataset.py and more, this is only useful for, as the name implies, creating custom datasets.

**Comment by WinglokWong616** [comment]
Well thanks!
