### ISSUE TITLE
Transferring labelfusion-generated data with multi-object labels

### ISSUE THREAD

**Issue by WinglokWong616** [hygxy/ma_densefusion#6]
Hi! Me again.
It seems that your _generatedata.py_ is meant for data with single object label. Have you ever tried trasferring multi-object labels in one single image?

**Comment by hygxy** [comment]
this repo doesn't contain a file called "generatedata.py". Do you mean "generategt.py"? 
No, i haven't tried, but it seems easy, what's your difficulity?

**Comment by WinglokWong616** [comment]
> this repo doesn't contain a file called "generatedata.py". Do you mean "generategt.py"? No, i haven't tried, but it seems easy, what's your difficulity?

I meant _generatedataset.py_, just wanna make sure your original code is designed for single object label. But it's okay, problem solved. Thx.
Just out of curiosity, I wonder why you chose to transfer your Labelfusion data to Linemod format and train with Linemod mode. 
'Cause I found it takes way less steps to transfer mine to YCB format and train with YCB mode. I think they share more similarity.

**Comment by hygxy** [comment]
Ok, glad to hear that the problem is solved.

The reason why I chose Linemod mode to train is simply that our
customer(who provides funding) thinks it's a better choice.
