### ISSUE TITLE
pred = torch.add(torch.bmm(model_points, base), points + pred_t), why?

### ISSUE THREAD

**Issue by zhw-github** [hygxy/ma_densefusion#7]
pred = torch.add(torch.bmm(model_points, base), points + pred_t), why?

**Comment by hygxy** [comment]
Why not?

**Comment by zhw-github** [comment]
why add points?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月06日 17:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hygxy/ma_densefusion] pred = torch.add(torch.bmm(model_points, base), points + pred_t), why? (Issue #7) |

Why not?

**Comment by hygxy** [comment]
please refer to https://github.com/j96w/DenseFusion/issues/119
